export enum CONFIG {
  NODE_ENV = 'NODE_ENV',
  SYSTEM_DB_HOST = 'SYSTEM_DB_HOST',
  SYSTEM_DB_PORT = 'SYSTEM_DB_PORT',
  SYSTEM_DB_USERNAME = 'SYSTEM_DB_USERNAME',
  SYSTEM_DB_PASSWORD = 'SYSTEM_DB_PASSWORD',
  SYSTEM_DB_NAME = 'SYSTEM_DB_NAME',
  JWT_SECRET = 'JWT_SECRET',

  MINIO_ENDPOINT = 'MINIO_ENDPOINT',
  MINIO_PORT = 'MINIO_PORT',
  MINIO_ACCESS_KEY = 'MINIO_ACCESS_KEY',
  MINIO_SECRET_KEY = 'MINIO_SECRET_KEY',
  MINIO_BUCKET_NAME = 'MINIO_BUCKET_NAME',
  MINIO_USE_SSL = 'MINIO_USE_SSL',
  MINIO_BEHIND_PROXY = 'MINIO_BEHIND_PROXY',

  TENANT_DOMAIN = 'TENANT_DOMAIN',

  AWS_REGION = 'AWS_REGION',
  AWS_ACCESS_KEY = 'AWS_ACCESS_KEY',
  AWS_SECRET_KEY = 'AWS_SECRET_KEY',
  AWS_SES_SENDER = 'AWS_SES_SENDER',

  COMPANY_API_KEY = 'COMPANY_API_KEY',
}

export const FILE_SIZE = 5 * 1024 * 1024;
